# version: "3.8"
# services:
#   backend:
#     image: 0efc2ac9c983 # Ваш ID образа из Docker Desktop
#     container_name: molscribe-api-v2
#     ports:
#       - "8000:8000"
#     volumes:
#       # Подключаем папку с весами (замените путь если папка называется иначе)
#       - ./backend/model.pth
#     deploy:
#       resources:
#         limits:
#           memory: 4G # Даем нейросети достаточно оперативной памяти
#     restart: always

version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    environment:
      - MODEL_PATH=/app/models/model.pth
    # Блок deploy крайне важен для проброса GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
