version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    environment:
      - MODEL_PATH=/app/models/model.pth
    # Блок deploy крайне важен для проброса GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
  rxn_backend:
    build:
      context: .
      dockerfile: ./rxn_backend/Dockerfile
    ports:
      - "8001:8000" # Разный внешний порт (8001), чтобы не было конфликта с MolScribe
    volumes:
      - ./rxn_backend:/app
      - ./rxn_backend/models:/app/models # Папка в папку!
    environment:
      - MODEL_PATH=/app/models/pix2seq_reaction_full.ckpt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
